name: Rust build and test all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: find . -depth 1 -type d -name "day*" -exec sh -c "cd {} && cargo build --verbose; cd .." \;
    - name: Run tests
      run: find . -depth 1 -type d -name "day*" -exec sh -c "cd {} && cargo test --verbose; cd .." \;
