name: Rust build and test all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build day01
      working-directory: day01
      run: cargo build --verbose
    - name: Run tests
      working-directory: day01
      run: cargo test --verbose
